export const griddd =`<div class="box">
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>  
  <div></div>
  <div></div>
  <div></div>
  <div></div>

</div>
`;
